### ISSUE TITLE
Priority-queues.md - Arne Sommer - Correction

### ISSUE THREAD

**Issue by arnesom** [LaurentRosenfeld/Perl-6-Miscellaneous#2]
Hi.

I wrote my own PriorityQueue module, which is described in my article, and included in the zip file. 

It didn't end up in the github repo for some reason.

**Comment by LaurentRosenfeld** [comment]
Hi Arne,

OK, I take your point, I was misled by the contents of the Github repo. I'll look at your zip file and fix my review accordingly.

Regards, Laurent.

**Comment by LaurentRosenfeld** [comment]
Hi Arne, I have updated my review to reflect your own PriorityQueue module.

I trust that you will find that satisfactory and close the issue, but please do not hesitate to open it again if you think something is still wrong or missing.
Best regards, Laurent.
