### ISSUE TITLE
Misspelled name

### ISSUE THREAD

**Issue by thundergnat** [LaurentRosenfeld/Perl-6-Miscellaneous#3]
Hi Laurent,

Extremely minor, but in your Prime-factorization review there should be no 't' in my last name.

    Stephen Schultze's implementation of...

should be:

    Stephen Schulze's implementation of...

Thanks!

Steve (thundergnat)

**Comment by LaurentRosenfeld** [comment]
Hi Steve,

sorry for having misspelled your name. This is silly on my part, since I knew how to spell your name (and typed it correctly twice). A typo that I missed when proofreading my text.

This is fixed now.

Cheers,
Laurent.
